FROM ubuntu:xenial-20200326

RUN apt-get update ; apt-get install -y python3 python3-pip

# add our requirements 
COPY ./requirements.txt /app/

WORKDIR /app

#install environment requirements
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
