FROM ubuntu:xenial-20200326

RUN apt-get update
# RUN apt-get install -y vim-gtk #this is a graphical app we dont need
# RUN apt-get install -y meld #this is a graphical app we dont need
RUN apt-get install -y git
RUN apt-get install -y gnupg2
# RUN apt-get install -y gitk #this is a graphical app we dont need
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-venv

# add our project files 
COPY . /app
WORKDIR /app

# make a virtualenv

RUN python3 -m venv app
RUN /bin/bash -c "source app/bin/activate"

#install environment requirements
RUN pip3 install -r requirements.txt


