FROM python:alpine3.11

COPY ./requirements.txt /app/

WORKDIR /app

#install environment requirements
RUN pip3 install -r /app/requirements.txt

ENTRYPOINT ["python3", "manage.py", "runserver", "0.0.0.0:8000"]