FROM ubuntu:xenial-20200326

RUN apt-get update
# RUN apt-get install -y vim-gtk #this is a graphical app we dont need
# RUN apt-get install -y meld #this is a graphical app we dont need
RUN apt-get install -y git
RUN apt-get install -y gnupg2
# RUN apt-get install -y gitk #this is a graphical app we dont need
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-venv
# RUN snap install atom --classic # we dont need atom - also you cant use snap in a container



